---
title: "Decompositions"
output:
  html_document:
    toc: yes
    toc_float: yes
  # pdf_document:
  #   toc: yes
---

```{=html}
<style>
  body {
  background-color: white;
  color: black;
}

pre, code {
  background-color: lightgray;
  color: grey;
}

pre:not([class]) {
  background-color: lightgray;
  color: black;
}

pre {
  border: 0px solid gray;
}

.hljs-string {
  color: darkgreen;
}

.hljs-number {
  color: blue;
}

.hljs-literal {
  color: brown;
}

.hljs-keyword {
  color: purple;
}

.tocify {
  border: 0px;
}

.list-group-item {
  background-color: lightgray;
  color: black;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  background-color: blue;
  border-color: blue;
  color: white;
}

h1, h2, h3, h4, h5, h6 {
  color: black;
}

</style>
```

# Libraries

```{r}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stargazer))
suppressPackageStartupMessages(library(forecast))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(stats))
suppressPackageStartupMessages(library(lfe))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(source("~/Documents/GitHub/MonetaryPolicyEffectOnNetInterestMargins/functions.R"))
```

# Reading data

```{r}
data <- read_csv("data/for_regressing/flattened.csv")
functioning <- read_csv("data/for_regressing/banks_groups/functioning_or_not/functioning.csv", show_col_types = FALSE)  %>% select(-OVDP)
not_functioning <- read_csv("data/for_regressing/banks_groups/functioning_or_not/not_functioning.csv", show_col_types = FALSE)  %>% select(-OVDP)
top25 <- read_csv("data/for_regressing/banks_groups/top25_or_not/top25.csv", show_col_types = FALSE)  %>% select(-OVDP)
rest <- read_csv("data/for_regressing/banks_groups/top25_or_not/rest.csv", show_col_types = FALSE)  %>% select(-OVDP)
gov <- read_csv("data/for_regressing/banks_groups/gov_or_private/gov.csv", show_col_types = FALSE)  %>% select(-OVDP)
private <- read_csv("data/for_regressing/banks_groups/gov_or_private/private.csv", show_col_types = FALSE)  %>% select(-OVDP)
```

# Generic model

```{r}
data$Bank <- as.factor(data$Bank)
model <- felm(NII ~ AE + LEV + CASH + IR + NCI + TA + SEC | Bank | 0 | Bank, data = data)
generate_stargazer_with_titles(list(model), c('Generic FE model'))
```

# Pre-2014

## Data

```{r}
df_pre2014 <- data[data$Date < "2014-01-01", ]
functioning_pre2014 <- functioning[functioning$Date < "2014-01-01", ]
not_functioning_pre2014 <- not_functioning[not_functioning$Date < "2014-01-01", ]
```

## General model for pre 2014 data

```{r}
modelpre2014 <- felm(NII ~ AE + LEV + CASH + IR + NCI + TA + SEC | Bank | 0 | Bank, data = df_pre2014)

generate_stargazer_with_titles(list(model, modelpre2014), c('Generic FE model', 'Pre 2014'))
```

## Functioning banks vs closed ones

```{r}
functioning_model_pre2014 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = functioning_pre2014)
not_functioning_model_pre2014 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = not_functioning_pre2014)

generate_stargazer_with_titles(list(functioning_model_pre2014, not_functioning_model_pre2014, modelpre2014), c('Functioning', 'Not functioning', 'Pre 2014'))
```

# Post-2014

## Data

```{r}
df_after2014 <- data[data$Date >= "2014-01-01", ]
top25_after2014 <- top25[top25$Date >= "2014-01-01", ]
rest_after2014 <- rest[rest$Date >= "2014-01-01", ]
```

## General model for post 2014 data

```{r}
model_after2014 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = df_after2014)

generate_stargazer_with_titles(list(model, model_after2014), c('Generic FE model', 'Post 2014'))
```

## Top 25 or not

```{r}
top25_model_after2014 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = top25_after2014)
rest_model_after2014 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = rest_after2014)

generate_stargazer_with_titles(list(top25_model_after2014, rest_model_after2014, model_after2014), c('Top 25', 'Rest', 'Post 2014'))
```

# 2017 to 2023 (2nd quart)

## Data

```{r}
df_after2017 <- data[data$Date >= "2017-01-01", ]
df_after2017pre2023 <- df_after2017[df_after2017$Date < "2023-07-01", ]
gov_after2017 <- gov[gov$Date >= "2017-01-01", ]
private_after2017 <- private[private$Date >= "2017-01-01", ]
gov_after2017pre2023 <- gov_after2017[gov_after2017$Date < "2023-07-01", ]
private_after2017pre2023 <- private_after2017[private_after2017$Date < "2023-07-01", ]
```

## General model

```{r}
model_after2017pre2023 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = df_after2017pre2023)

generate_stargazer_with_titles(list(model, model_after2014), c('Generic FE model', 'Post 2017, Pre 2023'))
```

## Gov. owned vs private banks

```{r}
gov_model_after2017pre2023 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = gov_after2017pre2023)
private_model_after2017pre2023 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = private_after2017pre2023)
model_model_after2017pre2023 <-  <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = private_after2017pre2023)

generate_stargazer_with_titles(list(gov_model_after2017pre2023, private_model_after2017pre2023, model_after2014), c('Gov', 'Private', 'General'))
```

# Pre 2014 to Post 2014 compared

```{r}
generate_stargazer_with_titles(list(modelpre2014, model_after2014), c('Pre 2014', 'Post 2014'))
```

# Post 2022

```{r}
df_after2022 <- data[data$Date >= "2022-01-01", ]
df_pre2022 <- data[data$Date < "2022-01-01", ]
df_after2014pre2022 <- df_after2014[df_after2014$Date < "2022-01-01", ]
model_after2022 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = df_after2022)
model_after2014pre2022 <- felm(NII ~ AE + LEV + CASH + NCI + SEC + TA + IR |  Bank | 0 | Bank, data = df_after2014pre2022)
generate_stargazer_with_titles(list(model_after2014pre2022, model_after2022), c('2014-2022', 'Post 2022'))
```